-- Crea tablas, indices, FKs y secuencia del modelo MENT_* segun BSV-CALIDAD (EXTRANET).
--   run_sqlcl.sh --profile local-extranet .../create_ment_model.sql

SET ECHO ON
SET FEEDBACK ON
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT === Creando modelo MENT_* (referencia BSV-CALIDAD) ===

-- ---------------------------------------------------------------------------
-- Tablas maestras
-- ---------------------------------------------------------------------------
CREATE TABLE MENT_CHANNEL (
  MECH_NU_CHANNEL   NUMBER(10,0),
  MECH_URL_SERVER   VARCHAR2(100),
  MECH_USER_SERVER  VARCHAR2(100),
  MECH_CLASS        VARCHAR2(100),
  MECH_DEFAULT_TO   VARCHAR2(120)
);

CREATE TABLE MENT_MENSAJE (
  MEME_MECA_NU_CAMPANA  NUMBER(10,0)  NOT NULL,
  MEME_NU_MENSAJE       NUMBER(10,0)  NOT NULL,
  MEME_TX_TITULO        VARCHAR2(100),
  MEME_TX_CUERPO        LONG,
  MEME_NU_DIAS_VIG      NUMBER(2,0),
  MEME_STATUS           VARCHAR2(250),
  MEME_FECH_STATUS      DATE,
  MEME_NU_INTENTOS      NUMBER,
  MEME_CD_CHANNEL       NUMBER,
  MEME_TIME_NEXT        NUMBER(5,0),
  CONSTRAINT MEME_PK PRIMARY KEY (MEME_MECA_NU_CAMPANA, MEME_NU_MENSAJE)
);

-- ---------------------------------------------------------------------------
-- Cola de mensajes push
-- ---------------------------------------------------------------------------
CREATE TABLE MENT_PUSH_MSG (
  MEPU_MECA_NU_CAMPANA  NUMBER(10,0),
  MEPU_NU_MENSAJE       NUMBER(10,0),
  MEPU_ID               NUMBER        NOT NULL,
  MEPU_FE_STATUS        TIMESTAMP(6),
  MEPU_FE_INICIO        DATE,
  CONSTRAINT MEPU_PK PRIMARY KEY (MEPU_ID),
  CONSTRAINT MEPU_FK_MEME FOREIGN KEY (MEPU_MECA_NU_CAMPANA, MEPU_NU_MENSAJE)
    REFERENCES MENT_MENSAJE (MEME_MECA_NU_CAMPANA, MEME_NU_MENSAJE)
);

CREATE INDEX MEPU_INDEX_1 ON MENT_PUSH_MSG (MEPU_MECA_NU_CAMPANA, MEPU_FE_INICIO, MEPU_NU_MENSAJE);

-- ---------------------------------------------------------------------------
-- Detalle / intentos (FK -> MENT_PUSH_MSG.MEPU_ID)
-- ---------------------------------------------------------------------------
CREATE TABLE MENT_TRY_PUSH_MSG (
  METR_ID          NUMBER,
  METR_STATUS      VARCHAR2(1),
  METR_FE_STATUS   TIMESTAMP(6),
  METR_NU_INTENTO  NUMBER(2,0),
  METR_DE_ERROR    VARCHAR2(600),
  CONSTRAINT METR_FK_MEPU FOREIGN KEY (METR_ID)
    REFERENCES MENT_PUSH_MSG (MEPU_ID)
);

CREATE INDEX MENT_INDEX_1 ON MENT_TRY_PUSH_MSG (METR_NU_INTENTO, METR_STATUS, METR_ID);

CREATE TABLE MENT_PARAM_PUSH_MSG (
  MEPA_MEPU_ID  NUMBER,
  MEPA_NAME     VARCHAR2(25),
  MEPA_VALUE    LONG,
  CONSTRAINT MEPA_FK_MEPU FOREIGN KEY (MEPA_MEPU_ID)
    REFERENCES MENT_PUSH_MSG (MEPU_ID)
);

CREATE INDEX INDEX_MENT_PARAM_PUSH_MSG_01 ON MENT_PARAM_PUSH_MSG (MEPA_MEPU_ID, MEPA_NAME);

CREATE TABLE MENT_ADDRESSEE_PUSH_MSG (
  MEAP_MEPU_ID         NUMBER,
  MEAP_ADDRESSES_TO    VARCHAR2(500),
  MEAP_ADDRESSES_CC    VARCHAR2(500),
  MEAP_ADDRESSES_BCC   VARCHAR2(500),
  MEAP_ADDRESSES_FROM  VARCHAR2(60),
  CONSTRAINT MEAD_FK_MEPU FOREIGN KEY (MEAP_MEPU_ID)
    REFERENCES MENT_PUSH_MSG (MEPU_ID)
);

CREATE INDEX INDX_ADDRESSEE_PUSH_MSG ON MENT_ADDRESSEE_PUSH_MSG (MEAP_MEPU_ID);

CREATE TABLE MENT_ATTACHMENT_PUSH_MSG (
  MEAT_MEPU_ID  NUMBER,
  MEAT_PATH     VARCHAR2(200),
  CONSTRAINT MEAT_FK_MEPU FOREIGN KEY (MEAT_MEPU_ID)
    REFERENCES MENT_PUSH_MSG (MEPU_ID)
);

-- ---------------------------------------------------------------------------
-- Secuencia para MEPU_ID (ibMsg: SEQ_MENT_MSG.NEXTVAL)
-- ---------------------------------------------------------------------------
CREATE SEQUENCE SEQ_MENT_MSG
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  NOCYCLE
  CACHE 20;

PROMPT === Modelo MENT_* creado ===

EXIT
