-- Llenado muestra: MENT_CHANNEL (1,2,4) y MENT_MENSAJE (0-1, 1-1, 21-1). INSERT directo.
-- Perfil: local-extranet
SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Vaciar cola dependiente antes de MENT_MENSAJE (FK MEPU_FK_MEME)
DELETE FROM MENT_TRY_PUSH_MSG;
DELETE FROM MENT_PARAM_PUSH_MSG;
DELETE FROM MENT_ADDRESSEE_PUSH_MSG;
DELETE FROM MENT_ATTACHMENT_PUSH_MSG;
DELETE FROM MENT_PUSH_MSG;
DELETE FROM MENT_MENSAJE;
DELETE FROM MENT_CHANNEL WHERE MECH_NU_CHANNEL IN (1, 2, 4);
COMMIT;

INSERT INTO MENT_CHANNEL (MECH_NU_CHANNEL, MECH_URL_SERVER, MECH_USER_SERVER, MECH_CLASS, MECH_DEFAULT_TO) VALUES (1, 'http://200.74.195.98:13031/smssegbanes', 'xEAypqnA', 'SMSChannelService', NULL);
INSERT INTO MENT_CHANNEL (MECH_NU_CHANNEL, MECH_URL_SERVER, MECH_USER_SERVER, MECH_CLASS, MECH_DEFAULT_TO) VALUES (2, 'smtp-relay.gmail.com:587', NULL, 'MailChannelService', NULL);
INSERT INTO MENT_CHANNEL (MECH_NU_CHANNEL, MECH_URL_SERVER, MECH_USER_SERVER, MECH_CLASS, MECH_DEFAULT_TO) VALUES (4, 'https://appserv.danaconnect.com/api/1.0/rest/conversation/CONVERSATIONID/start/data', 'webservices@banescosegurosve||Banesco01*', 'DannaChannelService', NULL);

INSERT INTO MENT_MENSAJE (MEME_MECA_NU_CAMPANA, MEME_NU_MENSAJE, MEME_TX_TITULO, MEME_TX_CUERPO, MEME_NU_DIAS_VIG, MEME_STATUS, MEME_FECH_STATUS, MEME_NU_INTENTOS, MEME_CD_CHANNEL, MEME_TIME_NEXT) VALUES (0, 1, NULL, '${MENSAJE_SINIESTRO}', NULL, NULL, NULL, 3, 1, 90);
INSERT INTO MENT_MENSAJE (MEME_MECA_NU_CAMPANA, MEME_NU_MENSAJE, MEME_TX_TITULO, MEME_TX_CUERPO, MEME_NU_DIAS_VIG, MEME_STATUS, MEME_FECH_STATUS, MEME_NU_INTENTOS, MEME_CD_CHANNEL, MEME_TIME_NEXT) VALUES (1, 1, 'Cotización Nro. ${NU_COTIZACION}', '' || CHR(10) || '<div id=":ul"><font size="2" color="#000000"><b>Venezuela, ${FECHA} </b></font>' || CHR(10) || '<br><br>' || CHR(10) || '<p align="justify">' || CHR(10) || '<font color="#000000" size="2" face="arial"></font>' || CHR(10) || '</p>' || CHR(10) || '<pre>' || CHR(10) || '<p align="justify">' || CHR(10) || '<font color="#000000" size="2" face="arial">' || CHR(10) || '<font face="Tahoma" size="2">Se gener&#243; la Cotizaci&#243;n ${NU_COTIZACION}, de Fecha ${COT_FECHA}<br></font>' || CHR(10) || '</font>' || CHR(10) || '</p>' || CHR(10) || '</pre>' || CHR(10) || '<br>' || CHR(10) || '<p align="justify">' || CHR(10) || '<br>' || CHR(10) || '<font face="Tahoma" size="2">' || CHR(10) || '<br><br><br><br><br>' || CHR(10) || '<b>Atentamente</b>' || CHR(10) || '<br><br><br>' || CHR(10) || '<b>Banesco Seguros, C.A.</b>' || CHR(10) || '<br><br><br>' || CHR(10) || '<br><br><br><br><br>' || CHR(10) || 'Esta es una cuenta de correo no monitoreada. Por favor, no responda o reenv&#237;e mensajes a esta cuenta.' || CHR(10) || '<br>' || CHR(10) || '</font>' || CHR(10) || '<br>      ' || CHR(10) || '</p>' || CHR(10) || '<p>' || CHR(10) || '</p>' || CHR(10) || '<br>' || CHR(10) || '' || CHR(10) || '<table width="100%"><tbody><tr><td align="left"><font size="2" color="#5BA261"><b>BANESCO SEGUROS, C.A. </b><br>Ciudad Banesco, Piso 3, Cuadrante D <br>Calle Lincoln, entre Av. Principal y Av. Leonardo Da Vinci <br>Urb. Bello Monte | <br>Caracas, Venezuela | <br>Telf: 0212.720.17.96 <br>WhatsApp: 0424-CONTIGO  (266.84.46) | <br><a href="http://www.banescoseguros.com.ve">www.banescoseguros.com.ve</a> | <br></font></td></tr></tbody></table>' || CHR(10) || '' || CHR(10) || '<br><br><br><div style="overflow:hidden"><hr><p align="justify"><font size="1"><span style="color:rgb(34,34,34);font-family:arial,sans-serif">La informaci&#243;n contenida en este correo electr&#243;nico y cualquier anexo es de car&#225;cter confidencial y es propiedad de Banesco Seguros S.A. S&#243;lo est&#225; permitido su uso, copia, transmisi&#243;n, recepci&#243;n o distribuci&#243;n a personas debidamente autorizadas. Si usted recibi&#243; este correo por error por favor destr&#250;yalo, elimine cualquier copia guardada en su sistema. </span><span style="color:rgb(34,34,34);font-family:arial,sans-serif">Usted no debe utilizar la informaci&#243;n contenida para ning&#250;n prop&#243;sito ni compartirla con otras personas.</span></font></p><hr></div><div></div><div>' || CHR(10) || '</div></div>' || CHR(10) || '', 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MENT_MENSAJE (MEME_MECA_NU_CAMPANA, MEME_NU_MENSAJE, MEME_TX_TITULO, MEME_TX_CUERPO, MEME_NU_DIAS_VIG, MEME_STATUS, MEME_FECH_STATUS, MEME_NU_INTENTOS, MEME_CD_CHANNEL, MEME_TIME_NEXT) VALUES (21, 1, '${ASUNTO_ACTEXP}', '' || CHR(10) || '<div id="">' || CHR(10) || '<p align="justify"><font color="#000000" size="2" face="arial"></font></p><pre>' || CHR(10) || '<p align="justify"><font color="#000000" size="2" face="arial"><font face="Tahoma" size="2">Estimado ${NOM_PERSONA},<br>Adjunto solicitud de recaudos en ocasi&#243;n al reclamo indicado en el asunto, agradecemos cargar a trav&#233;s de la carga de documentos, en la consulta del siniestro por la p&#225;gina web de <a href="http://www.banescoseguros.com.ve">Banesco SegurOnline.</a> Opci&#243;n Consultas - Siniestros - Opciones - Anexar Documentos.<br><br>${DOCS_EXP}<br><br>En caso de presentarse alguna duda o inquietud, comunicarse a trav&#233;s de nuestro Centro de Contacto 0212-7201796.</font></font></p></pre><br>' || CHR(10) || '<p align="justify"><br><font face="Tahoma" size="2"><br><br><br><b>Atentamente,</b><br><br><br><b>Banesco Seguros, C.A.</b><br><br><br><br><br><br>Esta es una cuenta de correo no monitoreada. Por favor, no responda o reenv&#237;e mensajes a esta cuenta.<br></font><br></p><br>' || CHR(10) || '<table width="100%"><tbody><tr><td align="left"><font size="2" color="#5BA261"><b>BANESCO SEGUROS, C.A. </b><br>Ciudad Banesco, Piso 3, Cuadrante D <br>Calle Lincoln, entre Av. Principal y Av. Leonardo Da Vinci <br>Urb. Bello Monte | <br>Caracas, Venezuela | <br>Telf: 0212.720.17.96 <br>WhatsApp: 0424-CONTIGO  (266.84.46) | <br><a href="http://www.banescoseguros.com.ve">www.banescoseguros.com.ve</a> | <br></font></td></tr></tbody></table><br><br><br>' || CHR(10) || '<div style="overflow:hidden"><hr><p align="justify"><font size="1"><span style="color:rgb(34,34,34);font-family:arial,sans-serif">La informaci&#243;n contenida en este correo electr&#243;nico y cualquier anexo es de car&#225;cter confidencial y es propiedad de Banesco Seguros S.A. S&#243;lo est&#225; permitido su uso, copia, transmisi&#243;n, recepci&#243;n o distribuci&#243;n a personas debidamente autorizadas. Si usted recibi&#243; este correo por error por favor destr&#250;yalo, elimine cualquier copia guardada en su sistema. </span><span style' || '="color:rgb(34,34,34);font-family:arial,sans-serif">Usted no debe utilizar la informaci&#243;n contenida para ning&#250;n prop&#243;sito ni compartirla con otras personas.</span></font></p><hr></div><div></div><div></div>' || CHR(10) || '</div>' || CHR(10) || '', 0, NULL, TO_DATE('2023-08-23 22:14:41','YYYY-MM-DD HH24:MI:SS'), 3, 4, NULL);

COMMIT;
EXIT
